# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

dependencies:
  - pre-commit=4.1.*
  - pip=25.0.*
  - git==2.47.*
  - poetry=2.0.*
  - gh=2.66.*
  - jupyter==1.1.*
  - pip:
      - reuse==5.0.2
      - build==1.2.2
      - twine==6.1.0
