# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

dependencies:
  - python==3.13.*
  - pip=25.0.*
  - gcc
  - jupyter==1.1.*
  - s3cmd==2.4.0
  - pip:
      - deepdiff==8.4.2
