# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

CHALLENGERS = {
    "glo12": {
        "label": "GLO12",
        "url": "https://data.marine.copernicus.eu/product/GLOBAL_ANALYSISFORECAST_PHY_001_024",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "Physics-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "IFS HRES",
        "resolution": "1/12°",
    },
    "glo12_1_degree": {
        "label": "GLO12",
        "url": "https://data.marine.copernicus.eu/product/GLOBAL_ANALYSISFORECAST_PHY_001_024",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "Physics-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "IFS HRES",
        "resolution": "1°",
    },
    "glonet": {
        "label": "GLONET",
        "url": "https://glonet.lab.dive.edito.eu",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12",
        "resolution": "1/4°",
    },
    "glonet_1_degree": {
        "label": "GLONET",
        "url": "https://glonet.lab.dive.edito.eu",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12",
        "resolution": "1°",
    },
    "glonet2": {
        "label": "GLONET2",
        "url": "https://glonet.lab.dive.edito.eu",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12\u00b0",
    },
    "glonet240": {
        "label": "GLONET240",
        "url": "https://glonet.lab.dive.edito.eu",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12\u00b0",
    },
    "glonet2_nofinetune": {
        "label": "GLONET2 no-finetune",
        "url": "https://glonet.lab.dive.edito.eu",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12\u00b0",
    },
    "glonet2_e248": {
        "label": "GLONET2 e248",
        "url": "https://glonet.lab.dive.edito.eu",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12\u00b0",
    },
    "glonet2_e239_noice": {
        "label": "GLONET2 e239 no ice",
        "url": "https://glonet.lab.dive.edito.eu",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12\u00b0",
    },
    "glonet2_correct_stats": {
        "label": "GLONET2 correct stats",
        "url": "https://glonet.lab.dive.edito.eu",
        "organisation": "Mercator Ocean",
        "organisation_url": "https://mercator-ocean.eu",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12\u00b0",
    },
    "langya": {
        "label": "LangYa",
        "url": "https://arxiv.org/abs/2412.18097",
        "organisation": "Institute of Oceanology, Chinese Academy of Sciences",
        "organisation_url": "https://english.qdio.cas.cn/",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12\u00b0",
    },
    "wenhai": {
        "label": "WenHai",
        "url": "https://www.nature.com/articles/s41467-025-57389-2",
        "organisation": "DOMES",
        "organisation_url": "http://iaos.ouc.edu.cn/DeepOceanMultispheresandEarthSystem/list.htm",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12°",
    },
    "wenhai_1_degree": {
        "label": "WenHai",
        "url": "https://www.nature.com/articles/s41467-025-57389-2",
        "organisation": "DOMES",
        "organisation_url": "http://iaos.ouc.edu.cn/DeepOceanMultispheresandEarthSystem/list.htm",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1°",
    },
    "xihe": {
        "label": "XiHe",
        "url": "https://arxiv.org/abs/2402.02995",
        "organisation": "NUDT",
        "organisation_url": "https://english.nudt.edu.cn/",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1/12°",
    },
    "xihe_1_degree": {
        "label": "XiHe",
        "url": "https://arxiv.org/abs/2402.02995",
        "organisation": "NUDT",
        "organisation_url": "https://english.nudt.edu.cn/",
        "method": "ML-based",
        "forecast_type": "Deterministic",
        "initial_conditions": "GLO12/IFS",
        "resolution": "1°",
    },
}

KNOWN_CHALLENGERS = list(CHALLENGERS.keys())
