# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

dependencies:
  - gcc
  - git==2.47.*
  - pip:
      - oceanbench==0.0.2
