# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

from enum import Enum


class OceanbenchEnvironmentVariable(Enum):
    OCEANBENCH_CHALLENGER_PYTHON_CODE_URI_OR_LOCAL_PATH = "OCEANBENCH_CHALLENGER_PYTHON_CODE_URI_OR_LOCAL_PATH"
    OCEANBENCH_OUTPUT_BUCKET = "OCEANBENCH_OUTPUT_BUCKET"
    OCEANBENCH_OUTPUT_PREFIX = "OCEANBENCH_OUTPUT_PREFIX"
    OCEANBENCH_STAGE = "OCEANBENCH_STAGE"
    OCEANBENCH_STAGE_DIR = "OCEANBENCH_STAGE_DIR"
    OCEANBENCH_STAGE_MAX_WORKERS = "OCEANBENCH_STAGE_MAX_WORKERS"
    OCEANBENCH_REMOTE_RETRIES = "OCEANBENCH_REMOTE_RETRIES"
    OCEANBENCH_NOTEBOOK_IOPUB_TIMEOUT_SECONDS = "OCEANBENCH_NOTEBOOK_IOPUB_TIMEOUT_SECONDS"
    OCEANBENCH_REGION = "OCEANBENCH_REGION"
