name: Check format
on: [push]
jobs:
  check-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '1.5.6-0'
          micromamba-binary-path: ${{ runner.temp }}/bin/micromamba
          environment-file: conda_environment.yaml
          environment-name: oceanbench
          condarc-file: .condarc
          cache-environment: true
          post-cleanup: 'all'
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d ' ' -f1)" >> "$GITHUB_ENV"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Check format
        run: make check-format
        shell: micromamba-shell {0}
