name: Check README update
on: [push]
jobs:
  check-readme-update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '1.5.6-0'
          micromamba-binary-path: ${{ runner.temp }}/bin/micromamba
          environment-file: conda_environment_test.yaml
          environment-name: oceanbench_test
          condarc-file: .condarc
          cache-environment: true
          post-cleanup: 'all'
      - name: Check README update
        run: |
          make check-readme-update
        shell: micromamba-shell {0}
